config/routes.rb
Ontimesheet::Application.routes.draw do
  devise_for :authors

  resources :commits
 		
  resources :repositories

  resources :author_repositories 

  resource :authors

   root :to => "commits#index"

   match ':controller(/:action(/:id(.:format)))'
end

app/models/commit.rb
class Commit < ActiveRecord::Base
  belongs_to :author
  belongs_to :repository
  validates_presence_of :sha

  after_create :create_author_repository
#  before_destroy :find_author_repositoy

  def create_author_repository
    if(AuthorRepository.where(:author => author , :repository => repository).empty?)
      AuthorRepository.create(:author => author , :repository => repository)
    end
  end

 # def find_author_repository
  #  if(Commit.where(:author => author , :repository => repository).count <= 1)
   #   AuthorRepository.where(:author => author , :repository => repository).destroy
    #end
  #end
end

app/controllers/commits_controller.rb
class CommitsController < ApplicationController
  before_filter :authenticate_author!, :only => [ :edit, :destroy, :create ]
  before_filter :is_owner , :only => [ :edit , :update ]
  # GET /commits
  # GET /commits.xml

  def index
    @commits = Commit.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @commits }
    end
  end

  # GET /commits/1
  # GET /commits/1.xml
  def show
    @commit = Commit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @commit }
    end
  end

  # GET /commits/new
  # GET /commits/new.xml
  def new
    @commit = Commit.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @commit }
    end
  end

  # GET /commits/1/edit
  def edit
    @commit = Commit.find(params[:id])
  end

  # POST /commits
  # POST /commits.xml
  def create
    @commit = Commit.new(params[:commit_entry])

    respond_to do |format|
      if @commit.save
        format.html { redirect_to(@commit, :notice => 'Commit was successfully created.') }
        format.xml  { render :xml => @commit, :status => :created, :location => @commit }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @commit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /commits/1
  # PUT /commits/1.xml
  def update
    @commit = Commit.find(params[:id])

    respond_to do |format|
      if @commit.update_attributes(params[:commit_entry])
        format.html { redirect_to(@commit, :notice => 'Commit was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @commit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /commits/1
  # DELETE /commits/1.xml
  def destroy
    @commit = Commit.find(params[:id])
    @commit.destroy

    respond_to do |format|
      format.html { redirect_to(commits_url) }
      format.xml  { head :ok }
    end
  end
  def is_owner
    if(current_author != Author.find(params[:id]))
      redirect_to (root_path , :notice => 'Prohibited')
    end
  end
end

app/helpers/commits_helper.rb
module CommitsHelper
end

app/views/commits/_form.html.erb
<% @commit_entry = @commit %>
<%= form_for(@commit) do |f| %>
  <% if @commit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commit.errors.count, "error") %> prohibited this commit from being saved:</h2>
      <ul>
      <% @commit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field">
    <%= f.label :Sha %><br />
    <%= text_field :commit_entry , :sha %>
  </div>
    
  <div class="field">
    <%= f.label :author %><br />
    <%= select( "commit_entry", "author_id", Author.all.collect { |p| [p.name, p.id] }, { :include_blank => true } ) %>
  </div>
  
  <div class="field">
    <%= f.label :repository %><br />
   <%=  select( "commit_entry", "repository_id", Repository.all.collect { |p| [p.name,p.id] }, { :include_blank => true } ) %>
  </div>

  <div class="field">
    <%= f.label :comment %><br />
    <%= text_field :commit_entry, :comment %>
  </div>

  <div class="field">
    <%= f.label :commented_at %><br />	
    <%=date_select :commit_entry, :commented_at%>   
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
 <% end %>

app/views/commits/edit.html.erb
<h1>Editing commit</h1>

<%= render 'form' %>

<%= link_to 'Show', @commit %> |
<%= link_to 'Back', commits_path %>

app/views/commits/index.html.erb
<h1>Listing commits</h1>

<table>
  <tr>
    <th>Sha</th>
    <th>Author</th>
    <th>Repository</th>
    <th>Comment</th>
    <th>Commented at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @commits.each do |commit| %>
  <tr>
    <td><%= commit.sha %></td>
    <td><%= commit.author.name %></td>
    <td><%= commit.repository.name%></td>
    <td><%= commit.comment %></td>
    <td><%= commit.commented_at %></td>
    <td><%= link_to 'Show', commit %></td>
    <td><%= link_to 'Edit', edit_commit_path(commit) %></td>
    <td><%= link_to 'Destroy', commit, :confirm => 'Are you sure?', :method => :delete %></td>

	
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Commit', new_commit_path %>

app/views/commits/new.html.erb
<h1>New commit</h1>

<%= render 'form' %>

<%= link_to 'Back', commits_path %>

app/views/commits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sha:</b>
  <%= @commit.sha %>
</p>

<p>
  <b>Author:</b>
  <%= @commit.author.name %>
</p>

<p>
  <b>Repository:</b>
  <%= @commit.repository.name %>
</p>

<p>
  <b>Comment:</b>
  <%= @commit.comment %>
</p>

<p>
  <b>Commented at:</b>
  <%= @commit.commented_at %>
</p>


<%= link_to 'Edit', edit_commit_path(@commit) %> |
<%= link_to 'Back', commits_path %>