config/routes.rb
Ontimesheet::Application.routes.draw do
  devise_for :authors

  resources :commits
 		
  resources :repositories

  resources :author_repositories 

  resource :authors

   root :to => "commits#index"

   match ':controller(/:action(/:id(.:format)))'
end

app/models/repository.rb
class Repository < ActiveRecord::Base
        has_many :Authors
	has_many :Commits
	validates_presence_of :name 
	validates_presence_of :type
	validates_presence_of :path
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_filter :authenticate_author!, :only => [ :edit , :update , ]
  # GET /repositories
  # GET /repositories.xml
  def index
    @repositories = Repository.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @repositories }
    end
  end

  # GET /repositories/1
  # GET /repositories/1.xml
  def show
    @repository = Repository.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @repository }
    end
  end

  # GET /repositories/new
  # GET /repositories/new.xml
  def new
    @repository = Repository.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @repository }
    end
  end

  # GET /repositories/1/edit
  def edit
    @repository = Repository.find(params[:id])
  end

  # POST /repositories
  # POST /repositories.xml
  def create
    @repository = Repository.new(params[:repository])

    respond_to do |format|
      if @repository.save
        format.html { redirect_to(@repository, :notice => 'Repository was successfully created.') }
        format.xml  { render :xml => @repository, :status => :created, :location => @repository }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @repository.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /repositories/1
  # PUT /repositories/1.xml
  def update
    @repository = Repository.find(params[:id])

    respond_to do |format|
      if @repository.update_attributes(params[:repository])
        format.html { redirect_to(@repository, :notice => 'Repository was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @repository.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /repositories/1
  # DELETE /repositories/1.xml
  def destroy
    @repository = Repository.find(params[:id])
    @repository.destroy

    respond_to do |format|
      format.html { redirect_to(repositories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/repositories/_form.html.erb
<%= form_for(@repository) do |f| %>
  <% if @repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
      <% @repository.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :repository_type %><br />
    <%= f.text_field :repository_type %>
  </div>
  <div class="field">
    <%= f.label :path %><br />
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :log_file %><br />
    <%= f.text_field :log_file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repositories/edit.html.erb
<h1>Editing repository</h1>

<%= render 'form' %>

<%= link_to 'Show', @repository %> |
<%= link_to 'Back', repositories_path %>

app/views/repositories/index.html.erb
<h1>Listing repositories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Repository type</th>
    <th>Path</th>
    <th>Log file</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @repositories.each do |repository| %>
  <tr>
    <td><%= repository.name %></td>
    <td><%= repository.repository_type %></td>
    <td><%= repository.path %></td>
    <td><%= repository.log_file %></td>
    <td><%= link_to 'Show', repository %></td>
    <td><%= link_to 'Edit', edit_repository_path(repository) %></td>
    <td><%= link_to 'Destroy', repository, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Repository', new_repository_path %>

app/views/repositories/new.html.erb
<h1>New repository</h1>

<%= render 'form' %>

<%= link_to 'Back', repositories_path %>

app/views/repositories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @repository.name %>
</p>

<p>
  <b>Repository type:</b>
  <%= @repository.repository_type %>
</p>

<p>
  <b>Path:</b>
  <%= @repository.path %>
</p>

<p>
  <b>Log file:</b>
  <%= @repository.log_file %>
</p>


<%= link_to 'Edit', edit_repository_path(@repository) %> |
<%= link_to 'Back', repositories_path %>